version: '3.3'
services:
  web:
    image: emj365/docker-build-webhook:1.0.9
    environment:
      - SECERT=secert-key
      - REPO_SSH_URL=git@github.com:emj365/prepsmith.git
      - REPO_URL=https://github.com/emj365/prepsmith
      - BRANCH=staging
      - TAG=emj365/prepsmith:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json
    secrets:
      - prepsmith-repo-key
    networks:
      - default
      - traefik-net
    deploy:
      restart_policy:
        condition: any
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:prepsmith-docker-build-webhook.emj365.com"

networks:
  traefik-net:
    external: true

secrets:
  prepsmith-repo-key:
    external: true
